CREATE USER lab7_user WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE lab7 TO lab7_user;

\c lab7

GRANT CONNECT ON DATABASE lab7 TO lab7_user;
GRANT USAGE ON SCHEMA public TO lab7_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO lab7_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO lab7_user;
ALTER ROLE lab7_user SET search_path TO public;